# Codecov configuration for TCWatch
coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 1%
        base: auto

  ignore:
    - "**/*.test.ts"
    - "**/*.test.tsx"
    - "**/*.spec.ts"
    - "**/*.spec.tsx"
    - "**/test-utils/**"
    - "**/mocks/**"
    - "**/fixtures/**"
    - "**/coverage/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/node_modules/**"
    - "**/*.d.ts"
    - "**/types/**"
    - "**/scripts/**"
    - "e2e-tests/**"

flags:
  backend:
    paths:
      - TC-Backend/src/
    carryforward: true
  frontend:
    paths:
      - TC-Frontend/
    carryforward: true
  mobile:
    paths:
      - TC-Frontend/
    carryforward: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true